import React, { useEffect, useRef, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import styles from './ResultDisplay.module.css';

interface LogEntry {
    agent: string;
    output: any;
}

interface ResultDisplayProps {
    logs: LogEntry[];
    result?: string;
    finalStatus: string;
}

export default function ResultDisplay({ logs, result, finalStatus }: ResultDisplayProps) {
    const logsEndRef = useRef<HTMLDivElement>(null);
    const [error, setError] = useState<string | null>(null);

    // Auto-scroll logs
    useEffect(() => {
        logsEndRef.current?.scrollIntoView({ behavior: "smooth" });
    }, [logs]);

    // Check for errors in logs
    useEffect(() => {
        const lastLog = logs[logs.length - 1];
        if (lastLog && JSON.stringify(lastLog.output).includes("LLM_ERROR")) {
            const errorMsg = JSON.stringify(lastLog.output).match(/LLM_ERROR: (.*)"/)?.[1] || "Unknown Error";
            setError(errorMsg);
        }
        if (finalStatus === 'FAILED') {
            // Check if failure was due to Planner validation
            const valError = logs.find(l => l.agent === "Planner" && JSON.stringify(l.output).includes("Invalid input"))
            if (valError) {
                setError("Invalid Request: Please provide a meaningful topic.");
            } else {
                setError("Task Execution Failed. Please check logs.");
            }
        }
    }, [logs, finalStatus]);

    const downloadLogs = () => {
        const element = document.createElement("a");
        const file = new Blob([JSON.stringify(logs, null, 2)], { type: 'application/json' });
        element.href = URL.createObjectURL(file);
        element.download = "agent_logs.json";
        document.body.appendChild(element);
        element.click();
    };

    const printReport = () => {
        const printWindow = window.open('', '_blank');
        if (printWindow && result) {
            // Clean up markdown syntax for "Top Notch" print look
            const cleanHtml = result
                .replace(/^# (.*$)/gm, '<h1>$1</h1>')
                .replace(/^## (.*$)/gm, '<h2>$1</h2>')
                .replace(/^### (.*$)/gm, '<h3>$1</h3>')
                .replace(/\*\*(.*)\*\*/gim, '<b>$1</b>')
                .replace(/\*(.*)\*/gim, '<i>$1</i>')
                .replace(/^\- (.*$)/gm, '<li>$1</li>')
                .replace(/\n\n/g, '<p></p>'); // Basic double newline to p

            printWindow.document.write(`
        <html>
          <head>
            <title>Research Report</title>
            <style>
              body { 
                  font-family: 'Times New Roman', serif; 
                  padding: 60px; 
                  max-width: 800px; 
                  margin: 0 auto; 
                  line-height: 1.6;
                  color: #111;
              }
              h1 { border-bottom: 2px solid #000; padding-bottom: 10px; margin-top: 0; font-size: 28px; }
              h2 { color: #333; margin-top: 30px; border-bottom: 1px solid #ddd; padding-bottom: 5px; font-size: 22px; }
              p { margin-bottom: 15px; text-align: justify; }
              li { margin-bottom: 5px; }
              .footer { 
                  margin-top: 50px; 
                  font-size: 12px; 
                  color: #666; 
                  text-align: center; 
                  border-top: 1px solid #eee; 
                  padding-top: 20px; 
              }
            </style>
          </head>
          <body>
            ${cleanHtml}
            <div class="footer">
                Generated by Groq-Powered Multi-Agent Orchestrator • ${new Date().toLocaleDateString()}
            </div>
            <script>
                document.close();
                window.print();
            </script>
          </body>
        </html>
      `);
        }
    };

    if (logs.length === 0 && !result) return null;

    return (
        <div className={styles.container}>

            {/* Error Banner */}
            {error && (
                <div className={styles.errorBanner}>
                    <div className={styles.errorIcon}>⚠️</div>
                    <div className={styles.errorText}>
                        <strong>SYSTEM ALERT:</strong> {error}
                    </div>
                </div>
            )}

            {logs.length > 0 && (
                <div className={styles.logsSection}>
                    <div className={styles.sectionHeader}>
                        <span className={styles.sectionTitle}>System Logs</span>
                        <div className={styles.headerControls}>
                            <button onClick={downloadLogs} className={styles.downloadBtn}>⬇ JSON</button>
                            <div className={styles.liveIndicator}>
                                <span className={styles.dot}></span> LIVE
                            </div>
                        </div>
                    </div>
                    <div className={`${styles.logs} ${error ? styles.logsError : ''}`}>
                        {logs.map((log, i) => {
                            const isError = JSON.stringify(log.output).includes("LLM_ERROR") || JSON.stringify(log.output).includes("Invalid input");
                            return (
                                <div key={i} className={`${styles.logEntry} ${isError ? styles.logEntryError : ''}`}>
                                    <span className={styles.logAgent}>::{log.agent}</span>
                                    <span className={styles.logContent}>
                                        {typeof log.output === 'string'
                                            ? log.output
                                            : JSON.stringify(log.output).substring(0, 120)}...
                                    </span>
                                </div>
                            );
                        })}

                        {/* Status Messages */}
                        {finalStatus === 'COMPLETED' && (
                            <div className={styles.logEntrySuccess}>
                                <span>::System</span>
                                <span>Task Execution Completed Successfully.</span>
                            </div>
                        )}

                        {/* Loading Cursor */}
                        {finalStatus !== 'COMPLETED' && finalStatus !== 'FAILED' && (
                            <div className={styles.cursorLine}>
                                <span className={styles.cursor}>_</span>
                            </div>
                        )}

                        <div ref={logsEndRef} />
                    </div>
                </div>
            )}

            {result && !error && (
                <div className={styles.resultCard}>
                    <div className={styles.resultHeader}>
                        <div className={styles.resultBadge}>FINAL REPORT</div>
                        <button onClick={printReport} className={styles.pdfBtn}>⬇ PDF / PRINT</button>
                    </div>
                    <div className={styles.resultContent}>
                        <ReactMarkdown>{result}</ReactMarkdown>
                    </div>
                </div>
            )}
        </div>
    );
}
